;;;;;;;;;; General ;;;;;;;;;;

[Intro Skip]
; Skips intro logos and autosave message.
Enabled = true

[Unlock Framerate]
; Unlocks the framerate and attempts to fix related bugs.
Enabled = true

;;;;;;;;;; Ultrawide ;;;;;;;;;;

[Fix Resolution]
; Unlocks available resolutions in-game.
Enabled = true

[Fix Aspect Ratio]
; Fixes various issues related to aspect ratio.
Enabled = true

[Fix HUD]
; Fixes various HUD issues.
Enabled = true

;;;;;;;;;; Graphics ;;;;;;;;;;

[LOD Tweaks]
; Set to true to enable the LOD settings below. 
Enabled = false
; Controls the LOD distance of terrain. Extra High = ResWidth (i.e 2560)
TerrainDistance = 8192
; Controls the LOD distance of models. Extra High = 128
ModelDistance = 512
; Control the LOD distance of grass tufts. Extra High = 250
GrassDistance = 1000

[Change FOV]
Enabled = true
FOV = 95.0
